name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - "container/**"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ""

defaults:
  run:
    working-directory: container

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x
          cache: "yarn"

      - name: install
        run: yarn

      - name: build
        run: yarn build

      - uses: shinyinc/action-aws-cli@v1.2
      - name: S3 sync
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
